### ISSUE TITLE
Suggestion for opening a slack channel

### ISSUE THREAD

**Issue by hiraksarkar** [rdocking/fusebench#1]
Hi, 
It would be great if we can open a slack channel, to discuss the goals and other parts of the project, before the competition starts.

**Comment by rdocking** [comment]
Sounds good - it looks like the event organizers are setting something up:

https://github.com/hackseq/hackseq_2017/issues/32

I've asked for permissions to join there - I'll try to invite you once I've got that set up.

**Comment by hiraksarkar** [comment]
cool!!
