### ISSUE TITLE
Convert STARfusion output to BEDPE

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#12]
From the example STARfusion output, write a simple parser to convert to BEDPE format

**Comment by sameerd** [comment]
I can start with this though I'm not exactly sure what I'm doing yet.

**Comment by rdocking** [comment]
Thanks Sameer! I've added you as a collaborator - once you've accepted that you should be able to assign yourself this issue.

**Comment by rdocking** [comment]
Also - please take a quick look at the data, then message me on Slack if you have questions about what we're trying to do here.

**Comment by rdocking** [comment]
This was completed by @sameerd - thanks!
