### ISSUE TITLE
Document data source - Atlas of Genetics

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#16]
Please answer the following questions about the Atlas of Genetics and Cytogenetics in Oncology and Haematology data source:

- Where is it located online?
- Is there an API?
- Are bulk downloads available?
- In general, what kinds of information are in this data source?

The answers should be uploaded to the wiki in an appropriate spot.

**Comment by rdocking** [comment]
- Located online at: http://atlasgeneticsoncology.org/
- Seems like there is no API or download access
- This database contains a lot of well-curated information - it may only be possible to query through the web interface though

**Comment by 382982408** [comment]
> Please answer the following questions about the Atlas of Genetics and Cytogenetics in Oncology and Haematology data source:
> 
> * Where is it located online?
> * Is there an API?
> * Are bulk downloads available?
> * In general, what kinds of information are in this data source?
> 
> The answers should be uploaded to the wiki in an appropriate spot.

Can you find out API or download access of the Atlas of Genetics and Cytogenetics in Oncology and Haematology Database? I really need this database for my research. Thank you very much.

**Comment by rdocking** [comment]
Hi there - at http://atlasgeneticsoncology.org/, under 'TABULATED FILES of ATLAS ITEMS', download the 'all items' text file.
