### ISSUE TITLE
Write simple BEDPE validator

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#18]
As a user, I want to have a simple script that talks a supposedly-BEDPE-formatted file as input, and checks whether that file actually conforms to the BEDPE format. 

All of our conventions for 'properly formatted' should be enforced by this tool.

**Comment by hiraksarkar** [comment]
I can take this one. The format should comply with http://bedtools.readthedocs.io/en/latest/content/general-usage.html#bedpe-format right?

**Comment by hiraksarkar** [comment]
working on this.

**Comment by rdocking** [comment]
Yep - that's the standard we're using - thanks!

**Comment by hiraksarkar** [comment]
#45 merged
