### ISSUE TITLE
Initial summary statistics for core BEDPE fields for a single tool

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#19]
From a BEDPE-formatted input file for a single tool, generate simple summary statistics (and, if possible, visualizations) of these statistics:

- How many events are reported?
- What is the number of inter-chromosomal and intra-chromosomal events?
- What is the distribution of values in the 'score' field?

**Comment by stefpiatek** [comment]
Oops tapped on assign myself, but overall would be quite keen to do this. It looks like most of the parsing has been done in python, so happy to do that, or would we prefer it in R?

**Comment by rdocking** [comment]
Hi Stef - whichever you're most comfortable with. Both Erica and I are mostly working in R over here, while Alex and Will are coding in Python.

**Comment by stefpiatek** [comment]
Cool sounds good, I guess R makes most sense. Looks pretty simple, what kind of output do we want, a simple Rmd generated report for the stats, or just a command line output to show you when you're running it what the summary is?

**Comment by rdocking** [comment]
I like the Rmd reports!
