### ISSUE TITLE
Document annotation source: COSMIC

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#29]
Please answer the following questions about the COSMIC data source:

- Where is it located online?
- Is there an API?
- Are bulk downloads available?

In general, what kinds of information are in this data source?
The answers should be uploaded to the wiki in an appropriate spot.

**Comment by wilcas** [comment]
I'll try to answer at least one of these questions in around 10 minutes, but anyone should feel free to take it over when I have to step out for my test.

**Comment by wilcas** [comment]
## Online Location
[COSMIC](http://cancer.sanger.ac.uk/cosmic)
[Cell Lines Database](http://cancer.sanger.ac.uk/cell_lines)

##API
It looks like you can submit HTML GET requests to COSMIC of the form
```
http://cancer.sanger.ac.uk/api/ga4gh/beacon?format=json&ref=?&dataset=cosmic&allele=?&pos=?&chrom=?
```
You specify a response `format`, the reference genome by number (for example GrCH38 would be specified with `ref=38`), the dataset (i.e. `dataset=cosmic`), the `allele`,  `position`, and `chrom`. Essentially just replace the question marks above. More information about querying the COSMIC database can be found at their [BEACON Project](http://cancer.sanger.ac.uk/cosmic/beacon) page.

Given that you can specify output as a JSON, this should be pretty straightforward to work with in python using the `requests` and `json` modules, both of which are in the "standard" library.

##Bulk Download
See [Complete Fusion Export](http://cancer.sanger.ac.uk/cosmic/download)

**Comment by rdocking** [comment]
I've summarized these comments on the 'Data Sets' page of the wiki - thanks @wilcas !
