### ISSUE TITLE
Convert PanCan fusion data to BEDPE format

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#34]
From the PanCan fusion data file at:

`/home/projects/hackseq17_3/annotation_sources/tumour_fusion_gene_data_portal/pancanfus.txt`

... write a simple parser to convert to BEDPE format. This will allow us to compare these annotations to existing fusion calls.

**Comment by hiraksarkar** [comment]
This file seems to contain binary characters. Is that alright?

**Comment by rdocking** [comment]
Probably something to do with the way I downloaded it - if you want, you can try downloading again from: http://54.84.12.177/PanCanFusV2/

**Comment by hiraksarkar** [comment]
Thanks !
