### ISSUE TITLE
Convert CIViC data to BEDPE format

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#36]
Write a small parser to convert the CIViC variant summary data from:

`/home/projects/hackseq17_3/annotation_sources/civic/01-Sep-2017-VariantSummaries.tsv`

into BEDPE format. This will let us better compare these annotations to existing fusion calls.

**Comment by hiraksarkar** [comment]
#38 CIViC converter committed.

**Comment by hiraksarkar** [comment]
Changes are also in #45
