### ISSUE TITLE
Convert ChimerDB DB to BEDPE format

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#37]
Convert the ChimerDB data files (which still need to be transferred to ORCA) to BEDPE format. This will let us better annotate existing fusion calls.

**Comment by rdocking** [comment]
Note that I'm still having trouble getting these onto ORCA - they are freely available to download from http://203.255.191.229:8080/chimerdbv31/mdownload.cdb though.

**Comment by eacton** [comment]
Okay, I'll work on this.

**Comment by rdocking** [comment]
Note - lets say this one is about ChimerKB
