### ISSUE TITLE
Convert COSMIC fusions to BEDPE format

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#39]
From the COSMIC db flat file of fusions, write a converter to convert to BEDPE format

**Comment by rdocking** [comment]
COSMIC fusion export is downloaded to:

`/home/projects/hackseq17_3/annotation_sources/cosmic/CosmicFusionExport.tsv`

**Comment by stefpiatek** [comment]
happy to take this after some food

**Comment by rdocking** [comment]
Thanks!

**Comment by stefpiatek** [comment]
Looking at the cosmic data, I can get the transcript so work out the chromosome from that. Some have HGVS from the transcript so I'll pick out the the genomic position for the start and end for them.

If they don't have a chromosome, g_start and g_end in both should I remove the fusion or keep eveything in?

**Comment by rdocking** [comment]
For now, we can omit them - it doesn't really make sense to keep them if we can't get a coordinate.
