### ISSUE TITLE
Convert FusionMap output to BEDPE format

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#4]
From the example FusionMap output, write a simple parser to convert to BEDPE format

**Comment by wilcas** [comment]
It's me, back at it again with some parsing

**Comment by wilcas** [comment]
Again assumed 0 based Positions. There are also some transcript positions and length information that I tacked on to the end of the file. See the [FusionMap](http://www.arrayserver.com/wiki/index.php?title=Fusion_SE_report) documentation on their output for more info.
