### ISSUE TITLE
Run validator and format conversions on AML cell line data

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#43]
Taking as input the AML cell line data under:

`/home/projects/hackseq17_3/datasets/aml_cell_line_examples/`

- Run the existing format converters to convert the output for each fusion caller to BEDPE format.
- Run the validator to check that the output parses as valid BEDPE
- (If it's available) run the summary stats tool

**Comment by rdocking** [comment]
Note that the Makefile under `pipeline` will do some of this - you can update that if you like

**Comment by eacton** [comment]
I think this has been done with the Makefile so I'll close this issue.
